version: '2'

services:
  gamersclubfinder-frontend:
    image: 'gamersclubfinder-frontend:latest'
    build:
      context: .
    container_name: gamersclubfinder-frontend
    ports:
      - "4200:4200"
    depends_on:
      - gamersclubfinder-backend

  gamersclubfinder-backend:
    image: 'gamersclubfinder-backend:latest'
    build:
      context: .
    container_name: gamersclubfinder-backend
    ports:
      - "8080:8080"
    depends_on:
      - gamersclubfinder-db
    environment:
      - SPRING_JPA_DATABASE=postgresql
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gamersclubfinder-db:5432/gamersclubfinder
      - SPRING_DATASOURCE_USERNAME=gamersclubfinder
      - SPRING_DATASOURCE_PASSWORD=gamersclubfinder
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  gamersclubfinder-db:
    image: 'postgres:13.1-alpine'
    container_name: gamersclubfinder-db
    environment:
      - POSTGRES_USER=gamersclubfinder
      - POSTGRES_PASSWORD=gamersclubfinder
    ports:
      - "5555:5432"
    volumes:
      - \private\var\lib\postgresql

volumes:
  gamersclubfinder-db:
    external: true