FROM openjdk:17-jdk-alpine
MAINTAINER douglasbello.com
COPY target/gamersclubfinder-0.0.1-SNAPSHOT.jar gamersclubfinder-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/gamersclubfinder-0.0.1-SNAPSHOT.jar"]