spring:
  application:
    name: gamersclubfinder
  profiles:
    active: test
  main:
    lazy-initialization: true
  jpa:
    open-in-view: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true